#!/bin/bash

# Find the PID of the 7-highlander process
PID=$(pgrep -f "7-highlander")

if [ -n "$PID" ]; then
    # Kill the 7-highlander process
    kill "$PID"
    echo "Stopped the 7-highlander process"
else
    echo "No 7-highlander process found"
fi
