#!/usr/bin/env bash
# This script displays the username, user id, and home directory path for each user in /etc/passwd

while IFS=':' read -r username x uid gid info home shell; do
    echo "$username:$uid:$home"
done < /etc/passwd
